done/done/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from tasks import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    # path('', TemplateView.as_view(template_name='index.html')),
    path('', include('tasks.urls')),
    path('api/', include([
        path('register/', views.CreateUserView.as_view(), name='register'),
        path('login/', views.login, name='login'),
        path('logout/', views.logout_view, name='logout'),
        path('quickTask/', views.QuickTaskEntryViewAPI.as_view(), name='quickTask'),
        path('NtoTask/', views.NtoTaskView.as_view(), name='NtoTask'),
        path('NtoTask/<int:pk>/', views.NtoTaskView.as_view(), name='task-detail'),
        path('NtoProject/', views.NtoProjectView.as_view(), name='NtoProject'),
        path('NtoProject/<int:pk>/', views.NtoProjectView.as_view(), name='project-detail'),
        path('getUser/', views.get_user, name='get_user'),
        path('get_tasks/', views.get_tasks, name='get_tasks'),
        path('get_new_tasks/', views.get_new_tasks, name='get_new_tasks'),
        path('get_contexts/', views.ContextView.as_view(), name='get_contexts'),
        path('get_contexts/<int:pk>/', views.ContextView.as_view(), name='ger_contexts_detail'),
        path('get_assignees/', views.AssigneeView.as_view(), name='get_assignees'),
        path('get_assignee/<int:pk>/', views.AssigneeView.as_view(), name='ger_assignees_detail'),
        path('get_calendars/', views.CalendarView.as_view(), name='get_calendars'),
        path('get_calendar/<int:pk>/', views.CalendarView.as_view(), name='get_calendar_detail'),
        path('get_projects/', views.get_projects, name='get_projects'),
        path('tasks/<int:task_id>/', views.delete_task, name='delete_task'),
        path('oauth2callback/', views.OAuth2CallbackView, name='oauth2callback'),
        path('user-token/', views.user_token_view, name='user-token'),
        path('IsConnectedToGoogleApiView/', views.IsConnectedToGoogleApiView.as_view(), name='IsConnectedToGoogleApiView'),
        path('sync-google-calendar/', views.SyncGoogleCalendarView.as_view(), name='sync-google-calendar'),
        path('unlink-google-calendar/', views.UnlinkView, name='unlink-google-calendar'),
    ])),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

done/tasks/urls.py
from django.urls import path
from . import views
from .views import CompoundPriorityView

urlpatterns = [
    path('', views.home, name='home'),
    path('sorry/', views.sorry, name='sorry'),
    path('QuickTaskEntry/', views.QuickTaskEntryView, name="QuickTaskEntry"),
    path('new-task-organizer/submit-task/', views.NewTaskOrganizerSubmitTask, name="NewTaskOrganizerSubmitTask"),
    path('new-task-organizer/', views.NewTaskOrganizerWelcome, name="NewTaskOrganizerWelcome"),
    path('new-task-organizer/delete-entry/', views.NewTaskOrganizerDelete, name="NewTaskOrganizerDelete"),
    path('new-task-organizer/submit-project/', views.NewTaskOrganizerSubmitProject, name="NewTaskOrganizerSubmitProject"),
    path('search/results/', views.project_filter_results_view, name='project_filter_results_view'),
    path('prioritizer/', views.Prioritizer, name="prioritizer"),
    path('save_tasks/', views.save_tasks, name='save_tasks'),
    path('save_projects/', views.save_projects, name='save_projects'),
    path('compound_priority/', CompoundPriorityView.as_view(), name='compound_priority'),
    path('api/tasks/', views.api_tasks_compound_priorities, name='api_tasks'),
    path('delete-completed-tasks/', views.delete_completed_tasks, name='delete_completed_tasks'),
    path('delete-completed-projects/', views.delete_completed_projects, name='delete_completed_projects'),
    path('contexts/', views.contexts, name='contexts'),
    path('update_context/', views.update_context, name='update_context'),
    path('add_context/', views.add_context, name='add_context'),
    path('delete_context/', views.delete_context, name='delete_context'),
    path('assignees/', views.assignees, name='assignees'),
    path('update_assignee/', views.update_assignee, name='update_assignee'),
    path('add_assignee/', views.add_assignee, name='add_assignee'),
    path('delete_assignee/', views.delete_assignee, name='delete_assignee'),
    path('table_task/', views.table_task, name='table_task'),
    path('table_project/', views.table_project, name='table_project'),
    path('update_projects/', views.update_projects, name='update_projects'),
    path('add_project/', views.add_project, name='add_project'),
    path('update_tasks/', views.update_tasks, name='update_tasks'),
    
    path('tasks/', views.user_tasks, name='tasks'),
    path('projects/', views.user_projects, name='projects'),
    path('task-update/', views.update_task_v2, name='update_task'),
    path('project-update/', views.update_project_v2, name='update_project'),
    path('task-get/', views.get_tasks_v2, name='get_tasks'),
    path('project-get/', views.get_projects_v2, name='get_projects'),
    path('create_task/', views.create_task_v2, name='create_task'),
    path('create_project/', views.create_project_v2, name='create_project'),
    path('delete_task/', views.delete_completed_tasks, name='delete_task'),
    path('delete_project/', views.delete_completed_projects, name='delete_project'),
]

done/tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator

class Assignee(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=200, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class Context(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=200, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

class Projects(models.Model):
    PRIORITIES = [
        ("A", "A"),
        ("B", "B"),
        ("C", "C"),
        ("D", "D"),
    ]
    STATUSES = [
        ('', 'No Status'),
        ("Co", "Completed"),
        ("Cn", "Cancelled"),
        ("De", "Delegated"),
        ("Ip", "In Process"),
        ("Ns", "Not Started"),
        ("Wa", "Wait for"),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project_priority = models.CharField(max_length=1, choices=PRIORITIES, null=True, blank=True)
    project_status = models.CharField(max_length=2, choices=STATUSES)
    project_complete = models.BooleanField(default=False)
    project_name = models.CharField(max_length=200)
    project_deadline = models.DateField(null=True, blank=True)
    
    def __str__(self):
        return self.project_name


class Tasks(models.Model):
    PRIORITIES = [
        ("A", "A"),
        ("B", "B"),
        ("C", "C"),
        ("D", "D"),
    ]
    STATUSES = [
        ('', 'No Status'),
        ("Co", "Completed"),
        ("Cn", "Cancelled"),
        ("De", "Delegated"),
        ("Ip", "In Process"),
        ("Ns", "Not Started"),
        ("Wa", "Wait for"),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    priority = models.CharField(max_length=1, choices=PRIORITIES, null=True, blank=True)
    status = models.CharField(max_length=2, choices=STATUSES, default='Ns')
    complete = models.BooleanField(default=False)
    name = models.CharField(max_length=200)
    deadline = models.DateField(null=True, blank=True)
    context = models.ForeignKey(Context, on_delete=models.CASCADE,null=True, blank=True)
    effort = models.IntegerField(null=True, blank=True)
    assignee = models.ForeignKey(Assignee, on_delete=models.CASCADE, null=True, blank=True)
    parent = models.ForeignKey(Projects, on_delete=models.CASCADE, null=True, blank=True)
    new_task = models.BooleanField(default=True)
    compound_priority = models.IntegerField(null=True, blank=True)
    

class Calendar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event_title = models.CharField(max_length=200)
    event_start = models.DateTimeField()
    event_end = models.DateTimeField()
    event_allDay = models.BooleanField(default=False)
    event_taskId = models.ForeignKey(Tasks, on_delete=models.CASCADE, null=True)
    last_updated = models.DateTimeField(auto_now=True)  # existing field
    last_sync = models.DateTimeField(null=True)  # new field
    recurrence_rule = models.TextField(null=True)  # new field
    gcal_id = models.CharField(max_length=255, null=True, blank=True)  # new field

    def __str__(self):
        return self.event_title


class UserToken(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    access_token = models.CharField(max_length=200)
    refresh_token = models.CharField(max_length=200)
    last_gCal_sync = models.DateTimeField(null=True, blank=True)

done/tasks/forms.py
from django.forms import ModelForm, Textarea
from .models import Tasks, Assignee, Context, Projects
from django import forms
from django.utils.translation import gettext_lazy as _

class DateInput(forms.DateInput):
    input_type = 'date'

class QuickTaskEntry(forms.ModelForm):
    class Meta:
        model=Tasks
        fields=['name']
        labels = {'name':_('')}
        widgets = {'name': Textarea(attrs={"cols": 80, "rows": 10}),}
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = 'Enter your task list separated by enter'
        self.fields['name'].widget.attrs.update({'class': 'quick_task_entry_form_text w-input'})
        

class NewTaskOrganizerTaskForm(forms.ModelForm):
    class Meta:
        model = Tasks
        widgets = {'deadline' : DateInput(),'parent':forms.RadioSelect()}
        fields = ['priority', 'name', 'deadline', 'context', 'effort', 'parent', 'new_task']
    
    def __init__(self, *args, **kwargs):
        # super().__init__(*args, **kwargs)
        # self.fields['effort'].widget.attrs['placeholder'] = 'time'
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user:
            self.fields['context'].queryset = Context.objects.filter(user=user)

class NewTaskOrganizerProjectForm(forms.ModelForm):
    class Meta:
        model = Projects
        widgets = {'project_deadline' : DateInput()}
        fields = ['project_priority', 'project_name', 'project_deadline']





#################### TESTS ############################
class TestForm(forms.ModelForm):
    class Meta:
        model = Tasks
        fields = ['priority', 'status', 'name', 'deadline', 'context', 'effort', 'assignee', 'parent']
        last_active = forms.DateField(widget=DateInput)
        
        
class Task_Form(forms.ModelForm):
    class Meta:
        model = Tasks
        fields = ['priority']

done/tasks/templates/tasks/apiV2_prioritizer.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="nto-header-div medium">
    <div class="nto-hrd-div centered">
        <div class="nto-hdr">
            <div class="done-logo-small">DONE</div>
            <div class="hdr-2">{% block pagetitle %}{% endblock pagetitle %}</div>
            <div>
                {% block switchbutton %}{% endblock switchbutton %}
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<link href="https://unpkg.com/tabulator-tables@4.9.3/dist/css/tabulator.min.css" rel="stylesheet">
<script type="text/javascript" src="https://unpkg.com/tabulator-tables@4.9.3/dist/js/tabulator.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<link rel="stylesheet" href="{% static 'tasks/tabulator_midnight.css' %}" />

{% block table %}
{% endblock table %}

<script>
    // hello boy!
    // hello boy!
    var project_priorities = {{ project_priorities|safe }};
    var project_statuses = {{ project_statuses|safe }};
    var task_priorities = {{ task_priorities|safe }};
    var task_statuses = {{ task_statuses|safe }};
    var contextNames = {{ context_names|safe }};
    var assigneeNames = {{ assignee_names|safe }};
    var parentNames = {{ project_names|safe }};
</script>
<script src="{% static 'tasks/apiv2_script.js' %}" id="url"></script>

{% endblock content%}

done/tasks/templates/tasks/apiV2_projects.html
{% extends 'tasks/apiV2_prioritizer.html' %}
{% block pagetitle %}Your Projects & tasks{% endblock pagetitle %}
{% block switchbutton %}<a href="{% url 'tasks' %}" class="submit-btn w-button">Show all tasks</a>{% endblock switchbutton %}
{% block table %}


<div class="tabulator-container">
  <div id="project-table"></div>
  <button class="submit-btn w-button" id="add-project-button">+ add a project </button>
</div>

<div class="tabulator-container">
  <div id="task-table"></div>
  <button class="submit-btn w-button" id="add-task-button">+ add a task</button>
</div>

<dialog class="dial-box-container" id="add-project-dialog">
  <h2 class='dial-box-hdr'>Add a new Project or the next project</h2>
  <form id="add-project-form">
    <div class="dial-box-form-field">
      <label class='dial-box-lbl' for="project_name">Name:</label>
      <input class="dial-box-form-input" type="text" id="project_name" name="project_name">
    </div>
    <div class="dial-box-form-field">
      <label class='dial-box-lbl' for="project_priority">Priority:</label>
      <input class="dial-box-form-input" type="text" id="project_priority" name="project_priority">
    </div>
    <div class="dial-box-form-field">
      <input class="submit-btn w-button" type="submit" value="Create Project">
      <button class="submit-btn w-button" id="close-project-dialog" type="button">Close</button>
    </div>
  </form>
</dialog>

<dialog class="dial-box-container" id="add-task-dialog">
  <h2 class='dial-box-hdr'>Add a new task or follow-up task</h2>
  <form id="add-task-form">
    <div class="dial-box-form-field">
      <label class='dial-box-lbl' for="name">Name:</label>
      <input class="dial-box-form-input" type="text" id="name" name="name">
    </div>
    <div class="dial-box-form-field">
      <label class='dial-box-lbl' for="priority">Priority:</label>
      <input class="dial-box-form-input" type="text" id="priority" name="priority">
    </div>
    <div class="dial-box-form-field">
      <input class="submit-btn w-button" type="submit" value="Create Task">
      <button class="submit-btn w-button" id="close-task-dialog" type="button">Close</button>
    </div>
  </form>
</dialog>

<script>
  var tabletype = 'project';
</script>

{% endblock table %}

done/tasks/templates/tasks/new-task-o-wizard.html
{% extends 'base.html' %}
{% block data-wf %}data-wf-page="652b53b37568770d043d1279" data-wf-site="652482ea837db348b1939c93"{% endblock data-wf %}
{% block title %}new task organizer wizard{% endblock title %}
{% load widget_tweaks %}
{% block content %}


  <div class="main-section">
    <!-- NEW TASK ORGANIZER HEADER -->
    <div class="w-form">
      <form id="wf-form-selector" name="wf-form-selector" data-name="selector" method="post" data-wf-page-id="652b53b37568770d043d1279" data-wf-element-id="4ba501e2-0b49-e4b5-74ba-597dd9c33121">
        <div class="nto-header-div">
          <div class="nto-hrd-div">
            <div class="nto-hdr">
              <div class="done-logo-small">DONE</div>
              <div class="hdr-2">New Task Organizer</div>
            </div>
            <div class="nto-prj-slctr-div">
              <div class="menu-hdr-blue">{{ task_qty }} remaining entries. Current:</div>
              <div class="project-name">{{ new_task_name }}</div>
            </div>
          </div>
          <div class="nto-inpt-slct-div">
            <div class="menu-hdr-div">
              <label for="" class="menu-hdr-grey">What is it?</label>
            </div>
            <label data-w-id="c5e5cd09-74e5-ca46-3c8a-03692abc5541" class="radio-btn-field w-radio">
              <input type="radio" id="task" name="input-type" value="task" data-name="input type" class="w-form-formradioinput radio-btn w-radio-input">
              <span class="menu-txt w-form-label" for="task">A Task</span>
            </label>
            <label data-w-id="c5e5cd09-74e5-ca46-3c8a-03692abc5545" class="radio-btn-field w-radio">
              <input type="radio" id="project-2" name="input-type" value="project" data-name="input type" class="w-form-formradioinput radio-btn w-radio-input">
              <span class="menu-txt w-form-label" for="project-2">A Project</span>
            </label>
            <label data-w-id="c5e5cd09-74e5-ca46-3c8a-03692abc5549" class="radio-btn-field w-radio">
              <input type="radio" id="not-actionable" name="input-type" value="not actionable" data-name="input type" class="w-form-formradioinput radio-btn w-radio-input">
              <span class="radio-button-label w-form-label" for="not-actionable">Non Actionable</span>
            </label>
          </div>
        </div>
      </form>
      <div class="w-form-done">
        <div>Thank you! Your submission has been received!</div>
      </div>
      <div class="w-form-fail">
        <div>Oops! Something went wrong while submitting the form.</div>
      </div>
    </div>

    <!-- NEW ENTRY IS TASK FORM -->
    <div data-w-id="78698cbd-15e1-ff16-772a-d14af70e56e6" style="display:none" class="w-form">
      <form id="wf-form-new-entry-form" name="wf-form-new-entry-form" data-name="new-entry-form" data-redirect="/new-task-organizer/" action="/new-task-organizer/submit-task/" method="post" class="form" data-wf-page-id="652b53b37568770d043d1279" data-wf-element-id="78698cbd-15e1-ff16-772a-d14af70e56e7">
        {% csrf_token %}
        <div id="not" class="nto-dtl-info-div">
          <div class="nto-dtl-info-lft-div">
            <div class="menu-hdr-grey">Details:</div>
          </div>
          <aside class="nto-dtl-info-rgh-div">
            <div class="nto-project-fltr">
              <div class="menu-txt-grey">Name:</div>
              {{ form.name|add_class:"task-name-frame w-input"}}
              <!-- <input type="text" class="task-name-frame w-input" maxlength="256" name="name-task" data-name="name-task" placeholder="original name of the input" id="name-task" required=""> -->
            </div>
            <div class="div-nto-details">
              <div class="priority-box">
                <label for="priority-task" class="menu-txt-grey">Priority:</label>
                {{ form.priority|add_class:"task-name-frame priority w-input"}}
                <!-- <input type="text" class="task-name-frame centered w-input" maxlength="256" name="priority-task" data-name="priority-task" placeholder="A" id="priority-task"></div> -->
              <div class="effort-box">
                <label for="effort-task" class="menu-txt-grey">Effort (min):</label>
                {{ form.effort|add_class:"task-name-frame effort w-input"}}
                {% comment %} <input type="text" class="task-name-frame centered w-input" maxlength="256" name="effort-task" data-name="effort-task" placeholder="25 min" id="effort-task"></div> {% endcomment %}
              <div class="deadline-box">
                <label for="id_deadline" class="menu-txt-grey">Deadline:</label>
                {{ form.deadline|add_class:"task-name-frame deadline w-input"}}
                {% comment %} <input type="text" class="task-name-frame deadline w-input" maxlength="256" name="deadline-task" data-name="deadline-task" placeholder="date" id="deadline-task"></div> {% endcomment %}
              <div class="context-box">
                <label for="context-task" class="menu-txt-grey">Context:</label>
                {{ form.context|add_class:"task-name-frame context w-input"}}
                <!-- <input type="text" class="task-name-frame centered w-input" maxlength="256" name="context-task" data-name="context-task" placeholder="work" id="context-task"></div> -->
            </div>
          </aside>
        </div>

        <div class="not-project-fltr-div">
          <div class="nto-project-fltr">
              <div class="menu-txt-grey">Filter</div>
              {% csrf_token %}
              <input class="form-control task-name-frame w-input" type="search"
                      name="search" placeholder="filter your project"
                      hx-get="/search/results/"
                      hx-trigger="keyup changed, search"
                      hx-target="#search-results"
                      hx-indicator=".htmx-indicator">
          </div>
        </div>
        {% comment %} <div class="nto-proj-lst-div"> {% endcomment %}
          <div id="search-results" class="nto-proj-lst-div">
      
                  {% include "tasks/project_filter_results.html" %}
      
          </div>
        {% comment %} </div> {% endcomment %}

        {% comment %} <div class="not-project-fltr-div">
          <div class="nto-project-fltr">
            <div class="menu-txt-grey">Filter</div>

            <input type="text" class="task-name-frame w-input" maxlength="256" name="filter-filter-3" data-name="Filter Filter 3" placeholder="filter your project" id="filter-filter-3">
          </div>
        </div>
        <div class="nto-proj-lst-div">



          {% for radio in form.parent %}
          <div class="nto-prj-btn-field w-radio">
              {{ radio.tag }}
              <label class="project-list-txt w-form-label" for="{{ radio.id_for_label }}">{{ radio.choice_label }}</label>
          </div>
          {% endfor %}

        </div> {% endcomment %}
        <div class="w-layout-hflex form-btn-bar">
          {% comment %} <input type="submit" name = "process" value="Process &amp; Next" data-wait="Please wait..." class="submit-btn w-button"> {% endcomment %}
          <button type="submit" name="action" value="pocess" class="submit-btn w-button">Process & Next</button>
          <input type="submit" value="Close" data-wait="Please wait..." class="submit-btn w-button">
        </div>
      </form>
      <div class="w-form-done">
        <div>Thank you! Your submission has been received!</div>
      </div>
      <div class="w-form-fail">
        <div>Oops! Something went wrong while submitting the form.</div>
      </div>
    </div>

    <!-- NEW ENTRY IS PROJECT FROM -->
    <div data-w-id="e371bd6b-262e-5b69-3cad-5070134018e4" style="display:none" class="w-form">
      <form id="wf-form-new-entry-form" name="wf-form-new-entry-form" data-name="new-entry-form" data-redirect="/new-task-organizer/" action="/new-task-organizer/submit-project/" method="post" class="form" data-wf-page-id="652b53b37568770d043d1279" data-wf-element-id="e371bd6b-262e-5b69-3cad-5070134018e5">
        {% csrf_token %}
        <div class="nto-dtl-info-div">
          <div class="nto-dtl-info-lft-div">
            <div class="menu-hdr-grey">Details:</div>
          </div>
          <aside class="nto-dtl-info-rgh-div">
            <div class="nto-project-fltr">
              <div class="menu-txt-grey">Name:</div>
              {{ form_project.project_name|add_class:"task-name-frame w-input"}}
              {% comment %} <input type="text" class="task-name-frame w-input" maxlength="256" name="name-project" data-name="name-project" placeholder="original name of the input" id="name-project" required=""> {% endcomment %}
            </div>
            <div class="div-nto-details">
              <div class="priority-box">
                <label for="priority-project" class="menu-txt-grey">Priority:</label>
                {{ form_project.project_priority|add_class:"task-name-frame priority w-input"}}
                {% comment %} <input type="text" class="task-name-frame centered w-input" maxlength="256" name="priority-project" data-name="priority-project" placeholder="A" id="priority-project"></div> {% endcomment %}
              <div class="deadline-box">
                <label for="deadline-project" class="menu-txt-grey">Deadline:</label>
                {{ form_project.project_deadline|add_class:"task-name-frame deadline w-input"}}
                {% comment %} <input type="text" class="task-name-frame centered w-input" maxlength="256" name="deadline-project" data-name="deadline-project" placeholder="date" id="deadline-project"> {% endcomment %}
              </div>
            </div>
          </aside>
        </div>
        <div class="not-proj-nxt-act-div">
          <div class="nto-project-fltr">
            <div class="menu-txt-grey">Next Action</div>
            {{ form_task.name|add_class:"task-name-frame w-input"}}
            {% comment %} <input type="text" class="task-name-frame w-input" maxlength="256" name="next-action-project" data-name="next-action-project" placeholder="enter the first action for this project" id="next-action-project"> {% endcomment %}
          </div>
        </div>
        <div class="w-layout-hflex form-btn-bar"><input type="submit" value="Process &amp; Next" data-wait="Please wait..." class="submit-btn w-button"><input type="submit" value="Close" data-wait="Please wait..." class="submit-btn w-button"></div>
      </form>
      <div class="w-form-done">
        <div>Thank you! Your submission has been received!</div>
      </div>
      <div class="w-form-fail">
        <div>Oops! Something went wrong while submitting the form.</div>
      </div>
    </div>

    <!-- NEW ENTRY IS NOT ACTIONABLE FORM -->
    <div data-w-id="6239a38c-1ca4-4b06-5bab-b17bb0bd6a55" style="display:none" class="w-form">
      <form id="wf-form-new-entry-form" name="wf-form-new-entry-form" data-name="new-entry-form" data-redirect="/new-task-organizer/" action="/new-task-organizer/delete-entry/" method="post" class="form" data-wf-page-id="652b53b37568770d043d1279" data-wf-element-id="6239a38c-1ca4-4b06-5bab-b17bb0bd6a56">
        {% csrf_token %}
        <div class="nto-dtl-info-div">
          <div class="nto-dtl-info-lft-div">
            <div class="menu-hdr-grey">Details:</div>
          </div>
          <aside class="nto-dtl-info-rgh-div">
            <div class="nto-project-fltr">
              <div class="menu-txt-grey">Name:</div>
              {{ form.name|add_class:"task-name-frame w-input"}}
              {% comment %} <input type="text" class="task-name-frame w-input" maxlength="256" name="input-name-delete" data-name="input-name-delete" placeholder="original name of the input" id="input-name-delete" required=""> {% endcomment %}
            </div>
          </aside>
        </div>
        <div class="w-layout-hflex form-btn-bar">
          {% comment %} <input type="submit" name = "delete" value="Delete &amp; next" data-wait="Please wait..." class="submit-btn w-button"> {% endcomment %}
          <button type="submit" name="action" value="delete" class="submit-btn w-button">Delete</button>
          <input type="submit" value="Close" data-wait="Please wait..." class="submit-btn w-button">
        </div>
      </form>
      <div class="w-form-done">
        <div>Thank you! Your submission has been received!</div>
      </div>
      <div class="w-form-fail">
        <div>Oops! Something went wrong while submitting the form.</div>
      </div>
    </div>

    <!-- DEFAULT VIEW -->
    <div data-w-id="1ec4b793-6b39-0e83-ab13-95c4cbd15a1c" class="w-form">
      <form id="wf-form-dummy-name-form" name="wf-form-dummy-name-form" data-name="dummy-name-form" method="post" class="form" data-wf-page-id="652b53b37568770d043d1279" data-wf-element-id="1ec4b793-6b39-0e83-ab13-95c4cbd15a1d">
        <div class="nto-dtl-info-div">
          <div class="nto-dtl-info-lft-div">
            <div class="menu-hdr-grey">Details:</div>
          </div>
          <aside class="nto-dtl-info-rgh-div">
            <div class="nto-project-fltr">
              {{ form.name|add_class:"task-name-frame w-input"}}
              <!-- <div class="menu-txt-grey">Name:</div>
              <input type="text" class="task-name-frame w-input" maxlength="256" name="input-name-delete-2" data-name="Input Name Delete 2" placeholder="original name of the input" id="input-name-delete-2" required=""> -->
            </div>
          </aside>
        </div>
      </form>

      <div class="w-form-done">
        <div>Thank you! Your submission has been received!</div>
      </div>
      <div class="w-form-fail">
        <div>Oops! Something went wrong while submitting the form.</div>
      </div>
    </div>
  </div>

  {% endblock content %}